# Generated by Django 3.1.4 on 2021-09-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
    ]
