# Generated by Django 3.1.4 on 2021-09-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_ordermodel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='created_on',
        ),
    ]
